### ISSUE TITLE
How to "destroy" animations?

### ISSUE THREAD

**Issue by mrcoles** [scriptex/AnimateMe#3]
Is there any way to disable AnimateMe after it has been applied?

Similarly, skrollr has: `skrollr.init().destroy();`

**Comment by scriptex** [comment]
Since I cannot see your initialization of AnimateMe (because it is in a private branch/fork), I am not sure what exactly is the use case so I will try to guess 🙂.

My guess is that you do not have access to the instance of AnimateMe and this is the reason why you need a custom event.

If that is not the case, you can refer to your instance and call `destroy` at any time. This is shown in the README.

If not, I will implement custom events for destroying and re-starting.
I am thinking of something like the code you wrote above: `animateme:disable` and `animateme:enable`.
These two events will be bound to the `window` object and in order to use them, you must dispatch a new event on the `window` object.

How does that sound?

**Comment by mrcoles** [comment]
Sorry, it wasn’t exactly clear what I was describing. I want the extension to be able to disable AnimateMe if it’s running on a site while it’s doing a screen capture, and if possible it could re-enable it once the screen capture is done. The custom events on window approach would work well (for sites that are using it and have updated to the latest version)!

**Comment by scriptex** [comment]
This is now implemented and published on [Github](https://github.com/scriptex/AnimateMe/releases/tag/0.6.0) and [NPM](https://www.npmjs.com/package/animateme). 

Please refer to the [README](https://github.com/scriptex/AnimateMe/blob/master/README.md#trigger-custom-events) for more info, although you already know how to do it 😄.

Let me know if there is anything else i can do for you.

**Comment by mrcoles** [comment]
Cool, thank you for being so responsive! Just to see if I’m getting this right…

1. I would trigger 'animateme:destroy' before I was to disable it
2. can I trigger 'animateme:start' once I’m done to re-enable it (will it maintain any custom settings from however it was originally initialized)?

**Comment by scriptex** [comment]
Yes! :) 
Just a note that It is `animateme:enable` instead of `animateme:start`.
